---
- name: Install k3s
  hosts: servers
  become: true

  tasks:
    - name: Download k3s installer script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/install_k3s.sh

    - name: Set installer script executable
      file:
        path: /tmp/install_k3s.sh
        mode: 'u+x'

    - name: Run k3s installer script
      command: /tmp/install_k3s.sh

    - name: Retrieve k3s node token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Display k3s node token
      debug:
        var: k3s_token.stdout
